##
## Makefile for jetpack2Tek3 in /home/vermeu_v/Documents/Synthesis_Pool/jetpack2Tek3_2016
## 
## Made by Valerian Vermeulen
## Login   <vermeu_v@epitech.net>
## 
## Started on  Fri Jul 14 10:53:32 2017 Valerian Vermeulen
## Last update Fri Jul 14 10:53:32 2017 Valerian Vermeulen
##
